### ISSUE TITLE
Documentation pages constantly throwing up new version message

### ISSUE THREAD

**Issue by spoco2** [react-hook-form/documentation#387] opened 2020-07-23 21:24 UTC
Documentation pages constantly throwing up "🔈 React Hook Form documentation has been updated. Would you like to reload to display the latest version?" on every page load, and until you say "cancel", as clicking "ok" just causes it to appear again

![image](https://user-images.githubusercontent.com/5827872/88340052-6b6b7800-cd7e-11ea-833c-0b4f380da11d.png)

**Comment by bluebill1049** [comment] 2020-07-23 22:30
oh really? that's a bug for gatsby then, can you still reproduce this? i can issue an report on this.

**Comment by spoco2** [comment] 2020-07-23 22:32
Yeah, loading the page now is still throwing that.

**Comment by bluebill1049** [comment] 2020-07-23 22:43
can you supply more browser details?

**Comment by spoco2** [comment] 2020-07-23 22:50
For sure :)

Version 84.0.4147.89 (Official Build) (64-bit)

I disabled all my extensions, and while it still does come up on every fresh page load (load page from url, or clicking on the reload button in browser), it does go away and stay away when clicking 'OK'

So, there seems like there may have been some interaction with extensions (react dev tools, LastPass and so on)

However it still shouldn't be coming up on initial page load as I'm not specifically loading the v5 docs or anything :)

**Comment by bluebill1049** [comment] 2020-07-23 22:53
> Version 84.0.4147.89 (Official Build) (64-bit)

Chrome? I will try to reproduce this myself first.

mac/pc?

**Comment by spoco2** [comment] 2020-07-23 22:55
I'm sucking at this aren't I!?

Chrome, on Mac, OS 10.15.6

**Comment by bluebill1049** [comment] 2020-07-23 22:58
This is crap... maybe try safari for now?

**Comment by spoco2** [comment] 2020-07-23 22:59
Oh, it's fine. It's not stopping me from using the docs. Just wanted you to know 👍

**Comment by pmaier983** [comment] 2020-07-24 00:11
I'm going to close this issue. It seems more like a Gatsby error than anything else, and I'm having trouble reproducing it. Will re-open if another user reports a similar experience. Thank you!

**Closed by pmaier983** 2020-07-24 00:11 UTC

**Comment by cpprookie** [comment] 2020-07-24 02:49
![image](https://user-images.githubusercontent.com/18083815/88356421-56044700-cd9a-11ea-9aaa-774c3a4b53c3.png)
I get this problem too. I thought that was a feature not a bug that gatsby may cache something in local. I believe you can reproduce ** after new release publishing**.
env: mac chrome 84.0.4147.89

**Comment by bluebill1049** [comment] 2020-07-24 02:54
no that's a feature, but the user reported that he couldn'rt close the dialogue.

**Comment by cpprookie** [comment] 2020-07-24 03:05
LOL, sorry for stupid mistake @bluebill1049 .

**Comment by jodyheavener** [comment] 2021-02-11 18:27
I was coming to report this as an issue but then found this thread. I definitely thought this was a bug because it seems to pop up fairly often and the message isn't clear that something had changed since I last looked. Would it be possible to _always_ show the latest documentation and have some way to link back to older versions?
