### ISSUE TITLE
issue : Application error: a client-side exception has occurred (see the browser console for more information). 

### ISSUE THREAD

**Issue by anglofawzy** [react-hook-form/documentation#974] opened 2023-06-13 18:06 UTC
### Version Number

7.44.3

### Codesandbox/Expo snack

.

### Steps to reproduce

![image](https://github.com/react-hook-form/react-hook-form/assets/90111639/14c3f793-373f-4801-a99a-7da9d951a9cf)

**this error show when open website react-hook-form on chrome or edge**

### Expected behaviour

normal website react-hook-form 

### What browsers are you seeing the problem on?

Chrome, Edge

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment] 2023-06-13 22:33
@aranlucas any idea on this? I couldn't reproduce this.

**Comment by aranlucas** [comment] 2023-06-13 23:29
Without logs, it's going to be hard to debug. Since it doesn't seem to be reproducible

But if I had to guess possible spots to break the page.
* https://github.com/react-hook-form/documentation/blob/901f1b7085fcc083dca788f9cbe74d4f3e515630/src/pages/_document.tsx#L12-L15 is being accessed without any null checks to see if script was downloaded. CDN could have been down for a moment.
* NextJS version issues with deployment.

Clear cache and refresh will probably work for this situation

**Comment by aranlucas** [comment] 2023-06-13 23:35
I'm leaning towards general deployment/NextJS/AWS issues today. I tried removing docSearch script, and I at least get a blue background.

**Comment by bluebill1049** [comment] 2023-06-13 23:51
Thanks a lot @aranlucas yes, I think it could be related to that. We can close this issue for now, until more information is provided.

**Closed by bluebill1049** 2023-06-13 23:51 UTC
Labels: bug

**Comment by anglofawzy** [comment] 2023-06-14 00:27
> could you share the console log for the error?

![image](https://github.com/react-hook-form/documentation/assets/90111639/37c73a29-29ac-4981-bcf5-61ca2bba5845)

**Comment by anglofawzy** [comment] 2023-06-14 00:36
**it's work now thsnks for all**

**Comment by aranlucas** [comment] 2023-06-14 01:10
https://github.com/react-hook-form/documentation/pull/975

Any's are the Javascript killers
