### ISSUE TITLE
Add Navigable `id`s to Heading Elements in the Docs

### ISSUE THREAD

**Issue by ITenthusiasm** [react-hook-form/documentation#739] opened 2022-02-21 19:40 UTC
## Request
I was wondering if it would be possible for HTML `id`s to get added to the documentation for React Hook Form? It could potentially increase ease of navigation.

In my case particularly, I'm writing an article that points people to the "Isolate Re-renders" section of the home page. It'd be great if readers could just go straight to that section immediately instead of having to visit the home page and scroll down.

It's a rather simple ask. But since it could potentially benefit the project, I figured it was worth bringing up.

---

For clarity, this is referring to the main site: https://react-hook-form.com/.

**Comment by Moshyfawn** [comment] 2023-02-27 03:17
I'm gonna close this in favour of #915 - a general issue for tracking docs updates.

Sorry it's taking so long to get to this.

Duplicate of #915

**Closed by Moshyfawn** 2023-02-27 03:17 UTC
Labels: status: working in progress, improve documentation
